// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WakeCommerceProject.Infra.Data.Context;

#nullable disable

namespace WakeCommerceProject.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531131806_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WakeCommerceProject.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Camiseta manga curta estampada",
                            Name = "Camiseta",
                            Price = 89.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Casaco moletom liso",
                            Name = "Casaco",
                            Price = 299.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            Description = "Calça jeans",
                            Name = "Calça",
                            Price = 399.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Boné vermelho e cinza",
                            Name = "Boné",
                            Price = 59.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tênis de corrida",
                            Name = "Tênis",
                            Price = 559.99m,
                            Stock = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
